name: "Pull Request Maven Build"
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build with Maven"
        run: mvn clean package -DskipTests --file ./pom.xml
